-- load vimrc lua file
require "vimrc.options"
require "vimrc.autocommands"
require "vimrc.keymaps"
require "vimrc.plugins"
require "vimrc.colorscheme"
require "plugins.cmp"
require "lsp"
-- require "vimrc.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
-- require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvimtree"
require "plugins.vimtex"
require "plugins.bufferline"
require "plugins.lualine"
-- require "plugins.toggleterm"
-- require "plugins.project"
-- require "plugins.impatient"
-- require "plugins.indentline"
-- require "plugins.alpha"
-- require "plugins.whichkey"
