-- load vimrc lua file
require "plugins.impatient"
require "vimrc.options"
require "vimrc.autocommands"
require "vimrc.keymaps"
require "vimrc.plugins"
require "vimrc.colorscheme"
require "plugins.cmp"
require "lsp"
require "plugins.telescope-settings"
require "plugins.treesitter"
require "plugins.autopairs"
-- require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvimtree"
require "plugins.vimtex"
require "plugins.bufferline"
require "plugins.lualine"
require "plugins.spectre"
require "plugins.startify"
require "plugins.closebuffers"
-- require "plugins.session-manager"
require "plugins.toggleterm"
-- require "plugins.project"
require "plugins.indentline"
-- require "plugins.alpha"
-- require "plugins.whichkey"
